# apiVersion: v1
# kind: Service
# metadata:
#   name: fastapi-service
#   namespace: fastapi-app
# spec:
#   selector:
#     app: fastapi
#   type: LoadBalancer
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8000


apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: fastapi-app
spec:
  selector:
    app: fastapi
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
